"""Image downloader behaviour, ported from tests/integration/image-downloader.test.js.

Cache filenames are checked against ``tests/name_oracle.json``, generated by the
original Node implementation, because a filename change would silently
invalidate every user's existing download cache.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from xhs_mcp.shared.errors import InvalidImageError
from xhs_mcp.shared.image_downloader import ImageDownloader, get_image_downloader

_NAME_ORACLE = json.loads((Path(__file__).parent / "name_oracle.json").read_text())

_JPEG_BYTES = b"\xff\xd8\xff" + b"\x00" * 20
_PNG_BYTES = b"\x89PNG\r\n\x1a\n" + b"\x00" * 20
_GIF_BYTES = b"GIF89a" + b"\x00" * 20
_WEBP_BYTES = b"RIFF\x00\x00\x00\x00WEBP" + b"\x00" * 20
_BMP_BYTES = b"BM" + b"\x00" * 20


@pytest.fixture
def downloader(tmp_path: Path) -> ImageDownloader:
    return ImageDownloader(str(tmp_path / "temp_images"))


@pytest.mark.parametrize(
    ("path", "expected"),
    [
        ("https://example.com/a.jpg", True),
        ("http://example.com/a.jpg", True),
        ("HTTPS://EXAMPLE.COM/A.JPG", True),
        ("  https://example.com/a.jpg  ", True),
        ("./local/a.jpg", False),
        ("/abs/path/a.jpg", False),
        ("C:\\images\\a.jpg", False),
        ("ftp://example.com/a.jpg", False),
        ("", False),
    ],
)
def test_is_image_url(path: str, expected: bool) -> None:
    assert ImageDownloader.is_image_url(path) is expected


@pytest.mark.parametrize(("url", "expected_name"), sorted(_NAME_ORACLE.items()))
def test_generate_file_name_matches_node_oracle(
    downloader: ImageDownloader, url: str, expected_name: str
) -> None:
    assert downloader._generate_file_name(url) == expected_name


def test_generate_file_name_is_stable(downloader: ImageDownloader) -> None:
    url = "https://example.com/photo.png"
    assert downloader._generate_file_name(url) == downloader._generate_file_name(url)


@pytest.mark.parametrize(
    ("data", "expected_valid", "expected_ext"),
    [
        (_JPEG_BYTES, True, "jpg"),
        (_PNG_BYTES, True, "png"),
        (_GIF_BYTES, True, "gif"),
        (_WEBP_BYTES, True, "webp"),
        (_BMP_BYTES, True, "bmp"),
        (b"<html>not an image</html>", False, ""),
        (b"short", False, ""),
        (b"", False, ""),
    ],
)
def test_validate_image_data(data: bytes, expected_valid: bool, expected_ext: str) -> None:
    is_valid, extension = ImageDownloader._validate_image_data(data)
    assert is_valid is expected_valid
    assert extension == expected_ext


def test_save_dir_is_created(tmp_path: Path) -> None:
    target = tmp_path / "nested" / "temp_images"
    ImageDownloader(str(target))
    assert target.is_dir()


async def test_download_image_rejects_non_url(downloader: ImageDownloader) -> None:
    with pytest.raises(InvalidImageError, match="Invalid image URL format"):
        await downloader.download_image("./local.jpg")


async def test_process_image_paths_accepts_local_files(
    downloader: ImageDownloader, tmp_path: Path
) -> None:
    image = tmp_path / "a.jpg"
    image.write_bytes(_JPEG_BYTES)

    assert await downloader.process_image_paths([str(image)]) == [str(image)]


async def test_process_image_paths_rejects_missing_local_file(
    downloader: ImageDownloader, tmp_path: Path
) -> None:
    with pytest.raises(InvalidImageError, match="Local image file not found"):
        await downloader.process_image_paths([str(tmp_path / "nope.jpg")])


async def test_process_image_paths_rejects_empty_input(
    downloader: ImageDownloader,
) -> None:
    with pytest.raises(InvalidImageError, match="No valid images found"):
        await downloader.process_image_paths([])


async def test_process_image_paths_preserves_local_then_downloaded_order(
    downloader: ImageDownloader, tmp_path: Path
) -> None:
    """Local paths keep their order and come first; downloads follow in URL order."""
    first = tmp_path / "first.jpg"
    second = tmp_path / "second.jpg"
    first.write_bytes(_JPEG_BYTES)
    second.write_bytes(_JPEG_BYTES)

    downloaded: list[str] = []

    async def fake_download_images(urls: list[str]) -> list[dict]:
        downloaded.extend(urls)
        return [
            {
                "originalUrl": url,
                "localPath": f"/cache/{index}.jpg",
                "cached": False,
                "fileSize": 1,
            }
            for index, url in enumerate(urls)
        ]

    downloader.download_images = fake_download_images  # type: ignore[assignment]

    result = await downloader.process_image_paths(
        [str(first), "https://e.com/x.jpg", str(second), "https://e.com/y.jpg"]
    )

    assert result == [str(first), str(second), "/cache/0.jpg", "/cache/1.jpg"]
    assert downloaded == ["https://e.com/x.jpg", "https://e.com/y.jpg"]


async def test_download_images_aggregates_failures(downloader: ImageDownloader) -> None:
    async def fake_download_image(url: str) -> dict:
        if url.endswith("bad.jpg"):
            raise InvalidImageError(f"boom for {url}")
        return {"originalUrl": url, "localPath": "/x.jpg", "cached": False, "fileSize": 1}

    downloader.download_image = fake_download_image  # type: ignore[assignment]

    with pytest.raises(InvalidImageError) as excinfo:
        await downloader.download_images(
            ["https://e.com/ok.jpg", "https://e.com/bad.jpg", "https://e.com/bad.jpg"]
        )

    error = excinfo.value
    assert error.message.startswith("Failed to download 2 of 3 images:")
    assert "https://e.com/bad.jpg: boom for https://e.com/bad.jpg" in error.message
    assert error.context["failedCount"] == 2
    assert error.context["successCount"] == 1
    assert error.context["totalCount"] == 3


async def test_cached_file_is_reused(downloader: ImageDownloader) -> None:
    url = "https://example.com/cached.jpg"
    cached_path = Path(downloader.get_save_dir()) / downloader._generate_file_name(url)
    cached_path.write_bytes(_JPEG_BYTES)

    result = await downloader.download_image(url)

    assert result["cached"] is True
    assert result["localPath"] == str(cached_path)
    assert result["fileSize"] == len(_JPEG_BYTES)


def test_get_image_downloader_reuses_instance_per_dir(tmp_path: Path) -> None:
    first = get_image_downloader(str(tmp_path / "one"))
    assert get_image_downloader(str(tmp_path / "one")) is first
    assert get_image_downloader(str(tmp_path / "two")) is not first
