"""Shared utilities, types, and services for XHS MCP Server."""

from .base_service import BaseService
from .config import ConfigManager, config_to_json_dict, get_config, set_config
from .cookies import (
    delete_cookies_file,
    get_cookies_file_path,
    get_cookies_info,
    load_cookies,
    save_cookies,
)
from .errors import (
    AuthenticationError,
    BrowserError,
    BrowserLaunchError,
    BrowserNavigationError,
    DeleteError,
    FeedError,
    FeedNotFoundError,
    FeedParsingError,
    InvalidImageError,
    LoginFailedError,
    LoginTimeoutError,
    NoteError,
    NoteParsingError,
    NotLoggedInError,
    ProfileError,
    PublishError,
    PublishFailedError,
    XHSError,
)
from .image_downloader import DownloadResult, ImageDownloader, get_image_downloader
from .logger import Logger, logger
from .profile import (
    clear_user_data_dir,
    ensure_user_data_dir,
    get_user_data_dir,
    is_owned_profile,
    is_profile_mode,
)
from .string_width import string_width
from .title_validator import (
    XHS_TITLE_CONSTRAINTS,
    XHSTitleConstraints,
    assert_title_width_valid,
    calculate_remaining_title_width,
    get_title_width,
    get_title_width_breakdown,
    truncate_title_to_width,
    validate_title_width,
)
from .types import Config
from .utils import (
    create_api_response,
    create_mcp_error_response,
    create_mcp_tool_response,
    is_array,
    is_number,
    is_string,
    retry_with_backoff,
    safe_error_handler,
    safe_json_parse,
    sleep,
    validate_publish_note_params,
    validate_required_params,
)
from .xhs_utils import (
    LOGIN_OK_SELECTOR,
    XHS_CREATOR_PUBLISH_URL,
    XHS_EXPLORE_URL,
    XHS_HOME_URL,
    XHS_SEARCH_URL,
    extract_initial_state,
    get_login_status_with_profile,
    is_element_in_viewport,
    is_logged_in,
    make_feed_detail_url,
    make_search_url,
)

__all__ = [
    "LOGIN_OK_SELECTOR",
    "XHS_CREATOR_PUBLISH_URL",
    "XHS_EXPLORE_URL",
    "XHS_HOME_URL",
    "XHS_SEARCH_URL",
    "AuthenticationError",
    "BaseService",
    "BrowserError",
    "BrowserLaunchError",
    "BrowserNavigationError",
    "Config",
    "ConfigManager",
    "DeleteError",
    "DownloadResult",
    "FeedError",
    "FeedNotFoundError",
    "FeedParsingError",
    "ImageDownloader",
    "InvalidImageError",
    "Logger",
    "LoginFailedError",
    "LoginTimeoutError",
    "NotLoggedInError",
    "NoteError",
    "NoteParsingError",
    "ProfileError",
    "PublishError",
    "PublishFailedError",
    "XHSError",
    "XHS_TITLE_CONSTRAINTS",
    "XHSTitleConstraints",
    "assert_title_width_valid",
    "calculate_remaining_title_width",
    "clear_user_data_dir",
    "config_to_json_dict",
    "create_api_response",
    "create_mcp_error_response",
    "create_mcp_tool_response",
    "delete_cookies_file",
    "ensure_user_data_dir",
    "extract_initial_state",
    "get_config",
    "get_cookies_file_path",
    "get_cookies_info",
    "get_image_downloader",
    "get_login_status_with_profile",
    "get_title_width",
    "get_user_data_dir",
    "get_title_width_breakdown",
    "is_array",
    "is_element_in_viewport",
    "is_number",
    "is_owned_profile",
    "is_profile_mode",
    "is_string",
    "is_logged_in",
    "load_cookies",
    "logger",
    "make_feed_detail_url",
    "make_search_url",
    "retry_with_backoff",
    "safe_error_handler",
    "safe_json_parse",
    "save_cookies",
    "set_config",
    "sleep",
    "string_width",
    "truncate_title_to_width",
    "validate_publish_note_params",
    "validate_required_params",
    "validate_title_width",
]
